/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $fetch: typeof import('@/lib/observability')['$fetch']
  const APP_LOG_ALL_FILTER_VALUE: typeof import('./app/composables/useAppLogs')['APP_LOG_ALL_FILTER_VALUE']
  const APP_LOG_LEVEL_OPTIONS: typeof import('./app/composables/useAppLogs')['APP_LOG_LEVEL_OPTIONS']
  const APP_LOG_SOURCE_OPTIONS: typeof import('./app/composables/useAppLogs')['APP_LOG_SOURCE_OPTIONS']
  const EffectScope: typeof import('vue')['EffectScope']
  const MODEL_DEBUG_ALL_FILTER_VALUE: typeof import('./app/composables/useModelDebugLogs')['MODEL_DEBUG_ALL_FILTER_VALUE']
  const MODEL_DEBUG_OPERATION_OPTIONS: typeof import('./app/composables/useModelDebugLogs')['MODEL_DEBUG_OPERATION_OPTIONS']
  const MODEL_DEBUG_PROVIDER_OPTIONS: typeof import('./app/composables/useModelDebugLogs')['MODEL_DEBUG_PROVIDER_OPTIONS']
  const PROMPT_STAGE_CONFIG: typeof import('./app/composables/useSettingsPrompts')['PROMPT_STAGE_CONFIG']
  const WORKFLOW_CATEGORY_CONFIG: typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_CATEGORY_CONFIG']
  const WORKFLOW_GEMINI_IMAGE_SIZES: typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_GEMINI_IMAGE_SIZES']
  const WORKFLOW_OPENAI_IMAGE_QUALITIES: typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_OPENAI_IMAGE_QUALITIES']
  const WORKFLOW_PANORAMA_SOURCE_MODES: typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_PANORAMA_SOURCE_MODES']
  const WORKFLOW_SEEDANCE_VIDEO_QUALITIES: typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_SEEDANCE_VIDEO_QUALITIES']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const createInitialAssetWorkbenchParseProgressState: typeof import('./app/composables/useAssetWorkbenchGeneration')['createInitialAssetWorkbenchParseProgressState']
  const createPinia: typeof import('pinia')['createPinia']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const definePageMeta: typeof import('./app/composables/useNuxtCompat')['definePageMeta']
  const defineStore: typeof import('pinia')['defineStore']
  const effectScope: typeof import('vue')['effectScope']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getBrowserNotificationStatus: typeof import('./app/composables/useGenerationCompletionNotification')['getBrowserNotificationStatus']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const markRaw: typeof import('vue')['markRaw']
  const navigateTo: typeof import('./app/composables/useNuxtCompat')['navigateTo']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const refreshBrowserNotificationStatus: typeof import('./app/composables/useGenerationCompletionNotification')['refreshBrowserNotificationStatus']
  const requestBrowserNotificationPermission: typeof import('./app/composables/useGenerationCompletionNotification')['requestBrowserNotificationPermission']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const sendSystemNotificationTest: typeof import('./app/composables/useGenerationCompletionNotification')['sendSystemNotificationTest']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAppLogs: typeof import('./app/composables/useAppLogs')['useAppLogs']
  const useAssetWorkbench: typeof import('./app/composables/useAssetWorkbench')['useAssetWorkbench']
  const useAssetWorkbenchAssetMedia: typeof import('./app/composables/useAssetWorkbenchAssetMedia')['useAssetWorkbenchAssetMedia']
  const useAssetWorkbenchAutoFlow: typeof import('./app/composables/useAssetWorkbenchAutoFlow')['useAssetWorkbenchAutoFlow']
  const useAssetWorkbenchCharacterActions: typeof import('./app/composables/useAssetWorkbenchCharacterActions')['useAssetWorkbenchCharacterActions']
  const useAssetWorkbenchGeneration: typeof import('./app/composables/useAssetWorkbenchGeneration')['useAssetWorkbenchGeneration']
  const useAssetWorkbenchPageState: typeof import('./app/composables/useAssetWorkbenchPageState')['useAssetWorkbenchPageState']
  const useAssetWorkbenchProjectIO: typeof import('./app/composables/useAssetWorkbenchProjectIO')['useAssetWorkbenchProjectIO']
  const useAssetWorkbenchSceneChat: typeof import('./app/composables/useAssetWorkbenchSceneChat')['useAssetWorkbenchSceneChat']
  const useAssetWorkbenchSceneChatActions: typeof import('./app/composables/useAssetWorkbenchSceneChatActions')['useAssetWorkbenchSceneChatActions']
  const useAssetWorkbenchSceneChatMentions: typeof import('./app/composables/useAssetWorkbenchSceneChatMentions')['useAssetWorkbenchSceneChatMentions']
  const useAssetWorkbenchSceneEditing: typeof import('./app/composables/useAssetWorkbenchSceneEditing')['useAssetWorkbenchSceneEditing']
  const useAssetWorkbenchSceneGeneration: typeof import('./app/composables/useAssetWorkbenchSceneGeneration')['useAssetWorkbenchSceneGeneration']
  const useAssetWorkbenchSceneManagement: typeof import('./app/composables/useAssetWorkbenchSceneManagement')['useAssetWorkbenchSceneManagement']
  const useAssetWorkflowMeta: typeof import('./app/composables/useAssetWorkflowMeta')['useAssetWorkflowMeta']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCharacter: typeof import('./app/composables/useCharacter')['useCharacter']
  const useClientUpdateCheck: typeof import('./app/composables/useClientUpdateCheck')['useClientUpdateCheck']
  const useCloudAdmin: typeof import('./app/composables/useCloudAdmin')['useCloudAdmin']
  const useCompletionNotificationSettings: typeof import('./app/composables/useCompletionNotificationSettings')['useCompletionNotificationSettings']
  const useConfirm: typeof import('./app/composables/useConfirm')['useConfirm']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useDesktopFfmpeg: typeof import('./app/composables/useDesktopFfmpeg')['useDesktopFfmpeg']
  const useDesktopUpdater: typeof import('./app/composables/useDesktopUpdater')['useDesktopUpdater']
  const useGenerationCompletionNotification: typeof import('./app/composables/useGenerationCompletionNotification')['useGenerationCompletionNotification']
  const useHead: typeof import('./app/composables/useNuxtCompat')['useHead']
  const useId: typeof import('vue')['useId']
  const useImagePromptReferenceEditor: typeof import('./app/composables/useImagePromptReferenceEditor')['useImagePromptReferenceEditor']
  const useImagePromptReferenceMentions: typeof import('./app/composables/useImagePromptReferenceMentions')['useImagePromptReferenceMentions']
  const useLink: typeof import('vue-router')['useLink']
  const useModel: typeof import('vue')['useModel']
  const useModelDebugLogs: typeof import('./app/composables/useModelDebugLogs')['useModelDebugLogs']
  const useProjectsIndexPage: typeof import('./app/composables/useProjectsIndexPage')['useProjectsIndexPage']
  const usePromptTemplateEditor: typeof import('./app/composables/usePromptTemplateEditor')['usePromptTemplateEditor']
  const usePromptTemplateEditorActions: typeof import('./app/composables/usePromptTemplateEditorActions')['usePromptTemplateEditorActions']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSceneAssetReferences: typeof import('./app/composables/useSceneAssetReferences')['useSceneAssetReferences']
  const useSceneDescriptionMentionEditor: typeof import('./app/composables/useSceneDescriptionMentionEditor')['useSceneDescriptionMentionEditor']
  const useSceneDescriptionMentionEditorActions: typeof import('./app/composables/useSceneDescriptionMentionEditorActions')['useSceneDescriptionMentionEditorActions']
  const useSeoMeta: typeof import('./app/composables/useNuxtCompat')['useSeoMeta']
  const useSettingsModelCatalog: typeof import('./app/composables/useSettingsModelCatalog')['useSettingsModelCatalog']
  const useSettingsModelTest: typeof import('./app/composables/useSettingsModelTest')['useSettingsModelTest']
  const useSettingsPrompts: typeof import('./app/composables/useSettingsPrompts')['useSettingsPrompts']
  const useSettingsWorkflowModels: typeof import('./app/composables/useSettingsWorkflowModels')['useSettingsWorkflowModels']
  const useSlots: typeof import('vue')['useSlots']
  const useState: typeof import('./app/composables/useNuxtCompat')['useState']
  const useStylePresetSettings: typeof import('./app/composables/useStylePresetSettings')['useStylePresetSettings']
  const useStylePresetSettingsActions: typeof import('./app/composables/useStylePresetSettingsActions')['useStylePresetSettingsActions']
  const useStylePresets: typeof import('./app/composables/useStylePresets')['useStylePresets']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useTheme: typeof import('./app/composables/useTheme')['useTheme']
  const useToast: typeof import('./app/composables/useToast')['useToast']
  const useVideoImport: typeof import('./app/composables/useVideoImport')['useVideoImport']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AppLogEntry } from './app/composables/useAppLogs'
  import('./app/composables/useAppLogs')
  // @ts-ignore
  export type { AssetWorkbenchTransitionType, CharacterData, SceneData } from './app/composables/useAssetWorkbench'
  import('./app/composables/useAssetWorkbench')
  // @ts-ignore
  export type { AssetWorkbenchParseProgressLogItem, AssetWorkbenchParseProgressState } from './app/composables/useAssetWorkbenchGeneration'
  import('./app/composables/useAssetWorkbenchGeneration')
  // @ts-ignore
  export type { PropAssetCategory, PropAssetMediaType, SceneConsistencyConfig, PropAsset, AssetWorkflowMeta } from './app/composables/useAssetWorkflowMeta'
  import('./app/composables/useAssetWorkflowMeta')
  // @ts-ignore
  export type { GenerateCharacterOptions } from './app/composables/useCharacter'
  import('./app/composables/useCharacter')
  // @ts-ignore
  export type { ClientUpdateInfo } from './app/composables/useClientUpdateCheck'
  import('./app/composables/useClientUpdateCheck')
  // @ts-ignore
  export type { ConfirmOptions } from './app/composables/useConfirm'
  import('./app/composables/useConfirm')
  // @ts-ignore
  export type { DesktopFfmpegStatus } from './app/composables/useDesktopFfmpeg'
  import('./app/composables/useDesktopFfmpeg')
  // @ts-ignore
  export type { DesktopUpdateInfo } from './app/composables/useDesktopUpdater'
  import('./app/composables/useDesktopUpdater')
  // @ts-ignore
  export type { BrowserNotificationPermissionState, BrowserNotificationStatus } from './app/composables/useGenerationCompletionNotification'
  import('./app/composables/useGenerationCompletionNotification')
  // @ts-ignore
  export type { ImagePromptReferenceTab } from './app/composables/useImagePromptReferenceEditor'
  import('./app/composables/useImagePromptReferenceEditor')
  // @ts-ignore
  export type { ModelDebugErrorInfo, ModelDebugMediaRef, ModelDebugLogEntry } from './app/composables/useModelDebugLogs'
  import('./app/composables/useModelDebugLogs')
  // @ts-ignore
  export type { PromptStageMeta, PromptTemplateGroup } from './app/composables/useSettingsPrompts'
  import('./app/composables/useSettingsPrompts')
  // @ts-ignore
  export type { CompatibleModel, WorkflowConfig, WorkflowData, WorkflowCategoryKey, WorkflowCategoryMeta, WorkflowCategorySummary } from './app/composables/useSettingsWorkflowModels'
  import('./app/composables/useSettingsWorkflowModels')
  // @ts-ignore
  export type { ToastVariant, ToastItem, ToastOptions } from './app/composables/useToast'
  import('./app/composables/useToast')
  // @ts-ignore
  export type { VideoImportTask, VideoImportArtifact, VideoImportStepRun, VideoImportTaskDetail, VideoImportConfig, VideoImportRetryStep } from './app/composables/useVideoImport'
  import('./app/composables/useVideoImport')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly $fetch: UnwrapRef<typeof import('@/lib/observability')['$fetch']>
    readonly APP_LOG_ALL_FILTER_VALUE: UnwrapRef<typeof import('./app/composables/useAppLogs')['APP_LOG_ALL_FILTER_VALUE']>
    readonly APP_LOG_LEVEL_OPTIONS: UnwrapRef<typeof import('./app/composables/useAppLogs')['APP_LOG_LEVEL_OPTIONS']>
    readonly APP_LOG_SOURCE_OPTIONS: UnwrapRef<typeof import('./app/composables/useAppLogs')['APP_LOG_SOURCE_OPTIONS']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly MODEL_DEBUG_ALL_FILTER_VALUE: UnwrapRef<typeof import('./app/composables/useModelDebugLogs')['MODEL_DEBUG_ALL_FILTER_VALUE']>
    readonly MODEL_DEBUG_OPERATION_OPTIONS: UnwrapRef<typeof import('./app/composables/useModelDebugLogs')['MODEL_DEBUG_OPERATION_OPTIONS']>
    readonly MODEL_DEBUG_PROVIDER_OPTIONS: UnwrapRef<typeof import('./app/composables/useModelDebugLogs')['MODEL_DEBUG_PROVIDER_OPTIONS']>
    readonly PROMPT_STAGE_CONFIG: UnwrapRef<typeof import('./app/composables/useSettingsPrompts')['PROMPT_STAGE_CONFIG']>
    readonly WORKFLOW_CATEGORY_CONFIG: UnwrapRef<typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_CATEGORY_CONFIG']>
    readonly WORKFLOW_GEMINI_IMAGE_SIZES: UnwrapRef<typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_GEMINI_IMAGE_SIZES']>
    readonly WORKFLOW_OPENAI_IMAGE_QUALITIES: UnwrapRef<typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_OPENAI_IMAGE_QUALITIES']>
    readonly WORKFLOW_PANORAMA_SOURCE_MODES: UnwrapRef<typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_PANORAMA_SOURCE_MODES']>
    readonly WORKFLOW_SEEDANCE_VIDEO_QUALITIES: UnwrapRef<typeof import('./app/composables/useSettingsWorkflowModels')['WORKFLOW_SEEDANCE_VIDEO_QUALITIES']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createInitialAssetWorkbenchParseProgressState: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchGeneration')['createInitialAssetWorkbenchParseProgressState']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly definePageMeta: UnwrapRef<typeof import('./app/composables/useNuxtCompat')['definePageMeta']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getBrowserNotificationStatus: UnwrapRef<typeof import('./app/composables/useGenerationCompletionNotification')['getBrowserNotificationStatus']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly navigateTo: UnwrapRef<typeof import('./app/composables/useNuxtCompat')['navigateTo']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refreshBrowserNotificationStatus: UnwrapRef<typeof import('./app/composables/useGenerationCompletionNotification')['refreshBrowserNotificationStatus']>
    readonly requestBrowserNotificationPermission: UnwrapRef<typeof import('./app/composables/useGenerationCompletionNotification')['requestBrowserNotificationPermission']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly sendSystemNotificationTest: UnwrapRef<typeof import('./app/composables/useGenerationCompletionNotification')['sendSystemNotificationTest']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAppLogs: UnwrapRef<typeof import('./app/composables/useAppLogs')['useAppLogs']>
    readonly useAssetWorkbench: UnwrapRef<typeof import('./app/composables/useAssetWorkbench')['useAssetWorkbench']>
    readonly useAssetWorkbenchAssetMedia: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchAssetMedia')['useAssetWorkbenchAssetMedia']>
    readonly useAssetWorkbenchAutoFlow: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchAutoFlow')['useAssetWorkbenchAutoFlow']>
    readonly useAssetWorkbenchCharacterActions: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchCharacterActions')['useAssetWorkbenchCharacterActions']>
    readonly useAssetWorkbenchGeneration: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchGeneration')['useAssetWorkbenchGeneration']>
    readonly useAssetWorkbenchPageState: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchPageState')['useAssetWorkbenchPageState']>
    readonly useAssetWorkbenchProjectIO: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchProjectIO')['useAssetWorkbenchProjectIO']>
    readonly useAssetWorkbenchSceneChat: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchSceneChat')['useAssetWorkbenchSceneChat']>
    readonly useAssetWorkbenchSceneChatActions: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchSceneChatActions')['useAssetWorkbenchSceneChatActions']>
    readonly useAssetWorkbenchSceneChatMentions: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchSceneChatMentions')['useAssetWorkbenchSceneChatMentions']>
    readonly useAssetWorkbenchSceneEditing: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchSceneEditing')['useAssetWorkbenchSceneEditing']>
    readonly useAssetWorkbenchSceneGeneration: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchSceneGeneration')['useAssetWorkbenchSceneGeneration']>
    readonly useAssetWorkbenchSceneManagement: UnwrapRef<typeof import('./app/composables/useAssetWorkbenchSceneManagement')['useAssetWorkbenchSceneManagement']>
    readonly useAssetWorkflowMeta: UnwrapRef<typeof import('./app/composables/useAssetWorkflowMeta')['useAssetWorkflowMeta']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCharacter: UnwrapRef<typeof import('./app/composables/useCharacter')['useCharacter']>
    readonly useClientUpdateCheck: UnwrapRef<typeof import('./app/composables/useClientUpdateCheck')['useClientUpdateCheck']>
    readonly useCloudAdmin: UnwrapRef<typeof import('./app/composables/useCloudAdmin')['useCloudAdmin']>
    readonly useCompletionNotificationSettings: UnwrapRef<typeof import('./app/composables/useCompletionNotificationSettings')['useCompletionNotificationSettings']>
    readonly useConfirm: UnwrapRef<typeof import('./app/composables/useConfirm')['useConfirm']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDesktopFfmpeg: UnwrapRef<typeof import('./app/composables/useDesktopFfmpeg')['useDesktopFfmpeg']>
    readonly useDesktopUpdater: UnwrapRef<typeof import('./app/composables/useDesktopUpdater')['useDesktopUpdater']>
    readonly useGenerationCompletionNotification: UnwrapRef<typeof import('./app/composables/useGenerationCompletionNotification')['useGenerationCompletionNotification']>
    readonly useHead: UnwrapRef<typeof import('./app/composables/useNuxtCompat')['useHead']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useImagePromptReferenceEditor: UnwrapRef<typeof import('./app/composables/useImagePromptReferenceEditor')['useImagePromptReferenceEditor']>
    readonly useImagePromptReferenceMentions: UnwrapRef<typeof import('./app/composables/useImagePromptReferenceMentions')['useImagePromptReferenceMentions']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useModelDebugLogs: UnwrapRef<typeof import('./app/composables/useModelDebugLogs')['useModelDebugLogs']>
    readonly useProjectsIndexPage: UnwrapRef<typeof import('./app/composables/useProjectsIndexPage')['useProjectsIndexPage']>
    readonly usePromptTemplateEditor: UnwrapRef<typeof import('./app/composables/usePromptTemplateEditor')['usePromptTemplateEditor']>
    readonly usePromptTemplateEditorActions: UnwrapRef<typeof import('./app/composables/usePromptTemplateEditorActions')['usePromptTemplateEditorActions']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSceneAssetReferences: UnwrapRef<typeof import('./app/composables/useSceneAssetReferences')['useSceneAssetReferences']>
    readonly useSceneDescriptionMentionEditor: UnwrapRef<typeof import('./app/composables/useSceneDescriptionMentionEditor')['useSceneDescriptionMentionEditor']>
    readonly useSceneDescriptionMentionEditorActions: UnwrapRef<typeof import('./app/composables/useSceneDescriptionMentionEditorActions')['useSceneDescriptionMentionEditorActions']>
    readonly useSeoMeta: UnwrapRef<typeof import('./app/composables/useNuxtCompat')['useSeoMeta']>
    readonly useSettingsModelCatalog: UnwrapRef<typeof import('./app/composables/useSettingsModelCatalog')['useSettingsModelCatalog']>
    readonly useSettingsModelTest: UnwrapRef<typeof import('./app/composables/useSettingsModelTest')['useSettingsModelTest']>
    readonly useSettingsPrompts: UnwrapRef<typeof import('./app/composables/useSettingsPrompts')['useSettingsPrompts']>
    readonly useSettingsWorkflowModels: UnwrapRef<typeof import('./app/composables/useSettingsWorkflowModels')['useSettingsWorkflowModels']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useState: UnwrapRef<typeof import('./app/composables/useNuxtCompat')['useState']>
    readonly useStylePresetSettings: UnwrapRef<typeof import('./app/composables/useStylePresetSettings')['useStylePresetSettings']>
    readonly useStylePresetSettingsActions: UnwrapRef<typeof import('./app/composables/useStylePresetSettingsActions')['useStylePresetSettingsActions']>
    readonly useStylePresets: UnwrapRef<typeof import('./app/composables/useStylePresets')['useStylePresets']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTheme: UnwrapRef<typeof import('./app/composables/useTheme')['useTheme']>
    readonly useToast: UnwrapRef<typeof import('./app/composables/useToast')['useToast']>
    readonly useVideoImport: UnwrapRef<typeof import('./app/composables/useVideoImport')['useVideoImport']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}