import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { spawnSync } from 'node:child_process'

const API_URL = 'https://api.oiioii.ai/knowledge/style_assets'
const STYLES_FILE = 'shared/types/styles.ts'
const DESCRIPTION_FILE = 'shared/types/style-descriptions.generated.ts'
const OUTPUT_DIR = 'public/styles'
const REQUEST_BODY = { data: { limit: 400, page: 1 } }

function extractLocalStyles() {
  const source = fs.readFileSync(STYLES_FILE, 'utf-8')
  const start = source.indexOf('const STYLE_PRESETS_BASE') !== -1
    ? source.indexOf('const STYLE_PRESETS_BASE')
    : source.indexOf('export const STYLE_PRESETS')
  const end = source.indexOf('export function getStylesByCategory')
  if (start === -1 || end === -1) {
    throw new Error(`Cannot parse ${STYLES_FILE}`)
  }

  const block = source.slice(start, end)
  const styleReg = /\{\s*id:\s*'([^']+)'[\s\S]*?name:\s*'([^']+)'[\s\S]*?nameEn:\s*'([^']+)'[\s\S]*?thumbnail:\s*'([^']+)'/g
  const items = []
  for (const m of block.matchAll(styleReg)) {
    items.push({
      id: m[1],
      name: m[2],
      nameEn: m[3],
      thumbnail: m[4],
    })
  }
  return items
}

async function fetchRemoteStyles() {
  const response = await fetch(API_URL, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(REQUEST_BODY),
  })

  if (!response.ok) {
    throw new Error(`Fetch failed: HTTP ${response.status}`)
  }

  const json = await response.json()
  if (!json?.data?.items || !Array.isArray(json.data.items)) {
    throw new Error('Unexpected API response shape')
  }

  return json.data.items.map((item) => ({
    name: (item.meta?.name || '').trim(),
    nameCn: (item.meta?.name_cn || '').trim(),
    url: item.meta?.url || '',
    content: (item.content || '').trim(),
  }))
}

function mapStyles(localStyles, remoteStyles) {
  const byCn = new Map(remoteStyles.map((r) => [r.nameCn, r]))
  const byEn = new Map(remoteStyles.map((r) => [r.name.toLowerCase(), r]))

  const mapped = []
  const unmatched = []

  for (const style of localStyles) {
    const hit = byCn.get(style.name) || byEn.get(style.nameEn.toLowerCase())
    if (!hit || !hit.url) {
      unmatched.push(style)
      continue
    }
    mapped.push({
      id: style.id,
      url: hit.url,
      content: hit.content,
    })
  }

  return { mapped, unmatched }
}

function writeDescriptionOverrides(mapped) {
  const lines = []
  lines.push('// This file is auto-generated by scripts/download-styles.mjs')
  lines.push('// Do not edit manually.')
  lines.push("export const STYLE_DESCRIPTION_OVERRIDES: Record<string, string> = {")
  for (const item of mapped) {
    lines.push(`  ${JSON.stringify(item.id)}: ${JSON.stringify(item.content)},`)
  }
  lines.push('}')
  lines.push('')
  fs.writeFileSync(DESCRIPTION_FILE, lines.join('\n'), 'utf-8')
}

function ensureCwebp() {
  const check = spawnSync('cwebp', ['-version'], { encoding: 'utf-8' })
  if (check.status !== 0) {
    throw new Error('cwebp not found. Please install webp tools first.')
  }
}

async function downloadAndConvert(mapped) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true })
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'style-sync-'))

  let ok = 0
  let fail = 0

  try {
    for (const item of mapped) {
      const srcPath = path.join(tmpDir, `${item.id}.src`)
      const outPath = path.join(OUTPUT_DIR, `${item.id}.webp`)

      try {
        const res = await fetch(item.url)
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        const buffer = Buffer.from(await res.arrayBuffer())
        fs.writeFileSync(srcPath, buffer)

        const convert = spawnSync('cwebp', ['-quiet', '-q', '82', srcPath, '-o', outPath], { encoding: 'utf-8' })
        if (convert.status !== 0) {
          throw new Error(convert.stderr || 'cwebp failed')
        }
        ok += 1
      } catch (err) {
        fail += 1
        console.error(`Failed ${item.id}: ${err.message}`)
      }

      if ((ok + fail) % 25 === 0) {
        console.log(`Processed ${ok + fail} / ${mapped.length}`)
      }
    }
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  }

  return { ok, fail }
}

async function main() {
  ensureCwebp()

  const localStyles = extractLocalStyles()
  const remoteStyles = await fetchRemoteStyles()
  const { mapped, unmatched } = mapStyles(localStyles, remoteStyles)

  writeDescriptionOverrides(mapped)
  const { ok, fail } = await downloadAndConvert(mapped)

  console.log(`Local styles: ${localStyles.length}`)
  console.log(`Remote styles: ${remoteStyles.length}`)
  console.log(`Mapped styles: ${mapped.length}`)
  console.log(`Downloaded: ${ok}`)
  console.log(`Failed: ${fail}`)
  if (unmatched.length > 0) {
    console.log(`Unmatched local styles (${unmatched.length}):`)
    console.log(unmatched.map((x) => x.id).join(', '))
  }
  console.log(`Generated: ${DESCRIPTION_FILE}`)
}

await main()
