const DOCUMENT_ID = '1257544'
const DOCUMENT_URL = `https://docs.volcengine.com/docs/6561/${DOCUMENT_ID}?lang=zh`
const DETAIL_URL = `https://docs.volcengine.com/api/doc/getDocDetail?LibraryID=6561&DocumentID=${DOCUMENT_ID}&AuditDocumentID=&type=online`
const OUTPUT_PATH = new URL('../shared/types/volcengine-voice-presets.generated.ts', import.meta.url)

interface DocDetailResponse {
  Result?: {
    MDContent?: string
    UpdatedTime?: string
  }
}

interface VoicePreset {
  id: string
  name: string
  scene: string
  language: string
  locale: string
  gender: 'female' | 'male' | 'unknown'
  capability: string
  tags: string
  model: '2.0' | '2.0-multilingual'
}

function cleanCell(value: string): string {
  return value
    .replace(/<br\s*\/?\s*>/gi, ' / ')
    .replace(/\[([^\]]+)]\([^)]+\)/g, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/\\\|/g, '|')
    .replace(/\\-/g, '-')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .replace(/(?:\s*\/\s*){2,}/g, ' / ')
    .trim()
}

function splitMarkdownRow(line: string): string[] {
  const placeholder = '\u0000PIPE\u0000'
  return line
    .trim()
    .replace(/\\\|/g, placeholder)
    .replace(/^\|/, '')
    .replace(/\|$/, '')
    .split('|')
    .map(cell => cleanCell(cell.replaceAll(placeholder, '|')))
}

function sectionLines(markdown: string, heading: string, nextHeading: string): string[] {
  const start = markdown.indexOf(heading)
  const end = markdown.indexOf(nextHeading, start + heading.length)
  if (start < 0 || end < 0) throw new Error(`未找到官方文档区段：${heading}`)
  return markdown.slice(start, end).split('\n')
}

function voiceLocale(id: string): string {
  const parts = id.toLowerCase().split('_')
  const knownLocales = new Set([
    'ar', 'bn', 'de', 'en', 'es', 'fil', 'fr', 'hi', 'id', 'it', 'ja', 'ko',
    'ms', 'nl', 'pl', 'pt', 'ru', 'ta', 'te', 'th', 'tr', 'vi', 'zh'
  ])
  return parts.find(part => knownLocales.has(part)) || parts[0] || 'unknown'
}

function voiceGender(id: string): VoicePreset['gender'] {
  if (id.includes('_female_')) return 'female'
  if (id.includes('_male_')) return 'male'
  return 'unknown'
}

function parseVoiceTable(lines: string[], model: VoicePreset['model']): VoicePreset[] {
  const voices: VoicePreset[] = []
  let currentScene = ''
  for (const line of lines) {
    if (!line.trim().startsWith('|') || /^\|?[\s:|-]+\|?$/.test(line.trim())) continue
    const cells = splitMarkdownRow(line)
    if (cells[0] === '场景' || cells[1] === '音色名称') continue
    const [sceneCell, name, id, language] = cells
    if (sceneCell) currentScene = sceneCell
    const validVoiceId = /^[A-Za-z][A-Za-z0-9_-]{7,255}$/.test(id)
    if (!name || !validVoiceId) continue
    voices.push({
      id,
      name,
      scene: currentScene || '其他',
      language: language || '未标注',
      locale: voiceLocale(id),
      gender: voiceGender(id),
      capability: model === '2.0-multilingual' ? (cells[5] || '') : (cells[4] || ''),
      tags: model === '2.0-multilingual' ? (cells[6] || '') : (cells[5] || ''),
      model
    })
  }
  return voices
}

const response = await fetch(DETAIL_URL, {
  headers: {
    Accept: 'application/json',
    Referer: DOCUMENT_URL,
    'User-Agent': 'Mozilla/5.0 Playlet voice catalog sync'
  }
})
if (!response.ok) throw new Error(`官方音色文档请求失败：HTTP ${response.status}`)

const payload = await response.json() as DocDetailResponse
const markdown = payload.Result?.MDContent
if (!markdown) throw new Error('官方音色文档缺少 MDContent')

const standard = parseVoiceTable(sectionLines(
  markdown,
  '"豆包语音合成模型2.0" 音色列表',
  '"豆包语音合成模型2.0" 多语种音色列表'
), '2.0')
const multilingual = parseVoiceTable(sectionLines(
  markdown,
  '"豆包语音合成模型2.0" 多语种音色列表',
  '"端到端实时语音大模型'
), '2.0-multilingual')

const uniqueVoices = [...new Map([...standard, ...multilingual].map(voice => [voice.id, voice])).values()]
  .sort((left, right) => left.name.localeCompare(right.name, 'zh-CN') || left.id.localeCompare(right.id))

if (uniqueVoices.length < 400) {
  throw new Error(`官方音色数量异常：标准 ${standard.length}，多语种 ${multilingual.length}，去重后 ${uniqueVoices.length} 个`)
}
if (!uniqueVoices.some(voice => voice.id === 'zh_female_vv_uranus_bigtts')) {
  throw new Error('官方音色目录缺少默认音色 Vivi 2.0')
}

const source = `// Generated by scripts/sync-volcengine-voice-presets.ts. Do not edit manually.\n\nexport interface VolcengineVoicePreset {\n  id: string\n  name: string\n  scene: string\n  language: string\n  locale: string\n  gender: 'female' | 'male' | 'unknown'\n  capability: string\n  tags: string\n  model: '2.0' | '2.0-multilingual'\n}\n\nexport const VOLCENGINE_VOICE_PRESETS_SOURCE = ${JSON.stringify({
  documentUrl: DOCUMENT_URL,
  documentUpdatedAt: payload.Result?.UpdatedTime || null,
  syncedAt: new Date().toISOString()
}, null, 2)} as const\n\nexport const VOLCENGINE_VOICE_PRESETS: VolcengineVoicePreset[] = ${JSON.stringify(uniqueVoices, null, 2)}\n`

await Bun.write(OUTPUT_PATH, source)
console.log(`已同步 ${uniqueVoices.length} 个火山官方音色（标准 ${standard.length}，多语种 ${multilingual.length}）`)
